# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `android_key_attestation` gem.
# Please instead update this file by running `bin/tapioca gem android_key_attestation`.

module AndroidKeyAttestation; end

class AndroidKeyAttestation::AuthorizationList
  def initialize(sequence); end

  def all_applications; end
  def creation_date; end
  def find_by_tag(tag); end
  def origin; end
  def purpose; end

  private

  def find_boolean(tag); end
  def find_optional_integer(tag); end
  def find_optional_integer_set(tag); end
  def find_time_milliseconds(tag); end
  def sequence; end
end

AndroidKeyAttestation::AuthorizationList::ACTIVE_DATE_TIME_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ALGORITHM_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ALLOW_WHILE_ON_BODY_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ALL_APPLICATIONS_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::APPLICATION_ID_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_APPLICATION_ID_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_BRAND_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_DEVICE_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_IMEI_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_MANUFACTURER_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_MEID_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_MODEL_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_PRODUCT_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ATTESTATION_ID_SERIAL_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::AUTH_TIMEOUT_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::BOOT_PATCH_LEVEL_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::CREATION_DATE_TIME_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::DIGEST_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::EC_CURVE_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::KEY_SIZE_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::NO_AUTH_REQUIRED_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ORIGINATION_EXPIRE_DATE_TIME_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ORIGIN_ENUM = T.let(T.unsafe(nil), Hash)
AndroidKeyAttestation::AuthorizationList::ORIGIN_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::OS_PATCH_LEVEL_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::OS_VERSION_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::PADDING_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::PURPOSE_ENUM = T.let(T.unsafe(nil), Hash)
AndroidKeyAttestation::AuthorizationList::PURPOSE_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ROLLBACK_RESISTANCE_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::ROOT_OF_TRUST_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::RSA_PUBLIC_EXPONENT_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::TRUSTED_CONFIRMATION_REQUIRED_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::TRUSTED_USER_PRESENCE_REQUIRED_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::UNLOCK_DEVICE_REQUIRED_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::USAGE_EXPIRE_DATE_TIME_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::USER_AUTH_TYPE_TAG = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::AuthorizationList::VENDOR_PATCH_LEVEL_TAG = T.let(T.unsafe(nil), Integer)
class AndroidKeyAttestation::CertificateVerificationError < ::AndroidKeyAttestation::Error; end
class AndroidKeyAttestation::ChallengeMismatchError < ::AndroidKeyAttestation::Error; end
class AndroidKeyAttestation::Error < ::StandardError; end
class AndroidKeyAttestation::ExtensionMissingError < ::AndroidKeyAttestation::Error; end
module AndroidKeyAttestation::FixedLengthSecureCompare; end
AndroidKeyAttestation::GEM_ROOT = T.let(T.unsafe(nil), String)

class AndroidKeyAttestation::KeyDescription
  def initialize(sequence); end

  def attestation_challenge; end
  def attestation_security_level; end
  def attestation_version; end
  def keymaster_security_level; end
  def keymaster_version; end
  def software_enforced; end
  def tee_enforced; end
  def unique_id; end

  private

  def sequence; end
end

AndroidKeyAttestation::KeyDescription::ATTESTATION_CHALLENGE_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::ATTESTATION_SECURITY_LEVEL_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::ATTESTATION_VERSION_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::KEYMASTER_SECURITY_LEVEL_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::KEYMASTER_VERSION_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::SECURITY_LEVEL_ENUM = T.let(T.unsafe(nil), Hash)
AndroidKeyAttestation::KeyDescription::SOFTWARE_ENFORCED_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::TEE_ENFORCED_INDEX = T.let(T.unsafe(nil), Integer)
AndroidKeyAttestation::KeyDescription::UNIQUE_ID_INDEX = T.let(T.unsafe(nil), Integer)

class AndroidKeyAttestation::Statement
  extend ::Forwardable

  def initialize(*certificates); end

  def attestation_certificate; end
  def attestation_security_level(*args, &block); end
  def attestation_version(*args, &block); end
  def key_description; end
  def keymaster_security_level(*args, &block); end
  def keymaster_version(*args, &block); end
  def software_enforced(*args, &block); end
  def tee_enforced(*args, &block); end
  def unique_id(*args, &block); end
  def verify_certificate_chain(root_certificates: T.unsafe(nil), time: T.unsafe(nil)); end
  def verify_challenge(challenge); end
end

AndroidKeyAttestation::Statement::EXTENSION_DATA_OID = T.let(T.unsafe(nil), String)
AndroidKeyAttestation::Statement::GOOGLE_ROOT_CERTIFICATES = T.let(T.unsafe(nil), Array)
AndroidKeyAttestation::VERSION = T.let(T.unsafe(nil), String)
