# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `autometal-piwik` gem.
# Please instead update this file by running `bin/tapioca gem autometal-piwik`.

module Piwik; end
class Piwik::API < ::Piwik::ApiModule; end
class Piwik::API::BulkRequest < ::Piwik::ApiResponse; end
class Piwik::API::DefaultMetricTranslations < ::Piwik::ApiResponse; end
class Piwik::API::DefaultMetrics < ::Piwik::ApiResponse; end
class Piwik::API::DefaultMetricsDocumentation < ::Piwik::ApiResponse; end
class Piwik::API::DefaultProcessedMetrics < ::Piwik::ApiResponse; end
class Piwik::API::Get < ::Piwik::ApiResponse; end
class Piwik::API::HeaderLogoUrl < ::Piwik::ApiResponse; end
class Piwik::API::LogoUrl < ::Piwik::ApiResponse; end
class Piwik::API::Metadata < ::Piwik::ApiResponse; end
class Piwik::API::PiwikVersion < ::Piwik::ApiResponse; end
class Piwik::API::ProcessedReport < ::Piwik::ApiResponse; end
class Piwik::API::ReportMetadata < ::Piwik::ApiResponse; end
class Piwik::API::RowEvolution < ::Piwik::ApiResponse; end
class Piwik::API::SegmentsMetadata < ::Piwik::ApiResponse; end
class Piwik::API::Settings < ::Piwik::ApiResponse; end
class Piwik::Actions < ::Piwik::ApiModule; end
class Piwik::Actions::Download < ::Piwik::ApiResponse; end
class Piwik::Actions::Downloads < ::Piwik::ApiResponse; end
class Piwik::Actions::EntryPageTitles < ::Piwik::ApiResponse; end
class Piwik::Actions::EntryPageUrls < ::Piwik::ApiResponse; end
class Piwik::Actions::ExitPageTitles < ::Piwik::ApiResponse; end
class Piwik::Actions::ExitPageUrls < ::Piwik::ApiResponse; end
class Piwik::Actions::Get < ::Piwik::ApiResponse; end
class Piwik::Actions::Outlink < ::Piwik::ApiResponse; end
class Piwik::Actions::Outlinks < ::Piwik::ApiResponse; end
class Piwik::Actions::PageTitle < ::Piwik::ApiResponse; end
class Piwik::Actions::PageTitles < ::Piwik::ApiResponse; end
class Piwik::Actions::PageTitlesFollowingSiteSearch < ::Piwik::ApiResponse; end
class Piwik::Actions::PageUrl < ::Piwik::ApiResponse; end
class Piwik::Actions::PageUrls < ::Piwik::ApiResponse; end
class Piwik::Actions::PageUrlsFollowingSiteSearch < ::Piwik::ApiResponse; end
class Piwik::Actions::PagesPerSearchColumn < ::Piwik::ApiResponse; end
class Piwik::Actions::SiteSearchCategories < ::Piwik::ApiResponse; end
class Piwik::Actions::SiteSearchKeywords < ::Piwik::ApiResponse; end
class Piwik::Actions::SiteSearchNoResultKeywords < ::Piwik::ApiResponse; end
class Piwik::Annotations < ::Piwik::ApiModule; end
class Piwik::Annotations::Add < ::Piwik::ApiResponse; end
class Piwik::Annotations::All < ::Piwik::ApiResponse; end
class Piwik::Annotations::AnnotationCountForDates < ::Piwik::ApiResponse; end
class Piwik::Annotations::Delete < ::Piwik::ApiResponse; end
class Piwik::Annotations::Get < ::Piwik::ApiResponse; end
class Piwik::Annotations::Save < ::Piwik::ApiResponse; end
class Piwik::ApiError < ::StandardError; end

class Piwik::ApiModule < ::Piwik::Base
  include ::Piwik::DataMethods
  include ::Piwik::DataMethods::InstanceMethods

  class << self
    def api_call(method, params); end
    def api_call_to_const(string, full = T.unsafe(nil)); end
    def available_methods(method_array); end
    def defaults; end
    def handle_api_call(method, params); end
    def method_missing(method, *args, &block); end
    def scoped_methods(&block); end
  end
end

class Piwik::ApiResponse < ::Piwik::Base
  include ::Piwik::DataMethods
  include ::Piwik::DataMethods::InstanceMethods
end

module Piwik::ApiScope
  mixes_in_class_methods ::Piwik::ApiScope::ClassMethods

  class << self
    def included(base); end
  end
end

module Piwik::ApiScope::ClassMethods
  def api_scope(name, scope_options = T.unsafe(nil), &block); end
end

class Piwik::Base
  include ::Piwik::Typecast
  include ::Piwik::Typecast::InstanceMethods
  include ::Piwik::ApiScope
  extend ::Piwik::ApiScope::ClassMethods

  def initialize(params = T.unsafe(nil)); end

  def attributes; end
  def attributes=(_arg0); end
  def call(method, params = T.unsafe(nil)); end
  def collection; end
  def config; end
  def created_at; end
  def delete; end
  def destroy; end
  def id; end
  def id_attr; end
  def method_missing(method, *args, &block); end
  def new?; end
  def parse_xml(xml); end
  def save; end
  def update; end

  class << self
    def call(method, params, piwik_url = T.unsafe(nil), auth_token = T.unsafe(nil)); end
    def collection; end
    def load(id); end
    def load_config_from_file; end
    def parse_xml(xml); end
    def reload(id); end
  end
end

class Piwik::CustomDimensions < ::Piwik::ApiModule; end
class Piwik::CustomDimensions::AvailableExtractionDimensions < ::Piwik::ApiResponse; end
class Piwik::CustomDimensions::AvailableScopes < ::Piwik::ApiResponse; end
class Piwik::CustomDimensions::ConfigureExistingCustomDimension < ::Piwik::ApiResponse; end
class Piwik::CustomDimensions::ConfigureNewCustomDimension < ::Piwik::ApiResponse; end
class Piwik::CustomDimensions::ConfiguredCustomDimensions < ::Piwik::ApiResponse; end
class Piwik::CustomDimensions::CustomDimension < ::Piwik::ApiResponse; end
class Piwik::CustomVariables < ::Piwik::ApiModule; end
class Piwik::CustomVariables::CustomVariables < ::Piwik::ApiResponse; end
class Piwik::CustomVariables::CustomVariablesValuesFromNameId < ::Piwik::ApiResponse; end

module Piwik::DataMethods
  include ::Piwik::Typecast
  include ::Piwik::Typecast::InstanceMethods
  include ::Piwik::DataMethods::InstanceMethods

  def data; end
  def data=(_arg0); end
  def value; end
  def value=(_arg0); end

  class << self
    def included(base); end
  end
end

module Piwik::DataMethods::InstanceMethods
  def initialize(opts = T.unsafe(nil)); end

  def empty?; end
  def method_missing(method, *args, &block); end
  def value; end
end

class Piwik::DevicesDetection < ::Piwik::ApiModule; end
class Piwik::DevicesDetection::Brand < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::BrowserEngines < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::BrowserVersions < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::Browsers < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::Model < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::OsFamilies < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::OsVersions < ::Piwik::ApiResponse; end
class Piwik::DevicesDetection::Type < ::Piwik::ApiResponse; end
class Piwik::Events < ::Piwik::ApiModule; end
class Piwik::Events::Action < ::Piwik::ApiResponse; end
class Piwik::Events::ActionFromCategoryId < ::Piwik::ApiResponse; end
class Piwik::Events::ActionFromNameId < ::Piwik::ApiResponse; end
class Piwik::Events::Category < ::Piwik::ApiResponse; end
class Piwik::Events::CategoryFromActionId < ::Piwik::ApiResponse; end
class Piwik::Events::CategoryFromNameId < ::Piwik::ApiResponse; end
class Piwik::Events::Name < ::Piwik::ApiResponse; end
class Piwik::Events::NameFromActionId < ::Piwik::ApiResponse; end
class Piwik::Events::NameFromCategoryId < ::Piwik::ApiResponse; end
class Piwik::ExampleApi < ::Piwik::ApiModule; end
class Piwik::ExampleApi::AnswerToLife < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::CompetitionDatatable < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::DescriptionArray < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::MoreInformationAnswerToLife < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::MultiArray < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::Null < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::Object < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::PiwikVersion < ::Piwik::ApiResponse; end
class Piwik::ExampleApi::Sum < ::Piwik::ApiResponse; end
class Piwik::Goals < ::Piwik::ApiModule; end
class Piwik::Goals::DaysToConversion < ::Piwik::ApiResponse; end
class Piwik::Goals::Get < ::Piwik::ApiResponse; end
class Piwik::Goals::Goal < ::Piwik::ApiResponse; end
class Piwik::Goals::Goals < ::Piwik::ApiResponse; end
class Piwik::Goals::ItemsCategory < ::Piwik::ApiResponse; end
class Piwik::Goals::ItemsName < ::Piwik::ApiResponse; end
class Piwik::Goals::ItemsSku < ::Piwik::ApiResponse; end
class Piwik::Goals::UpdateGoal < ::Piwik::ApiResponse; end
class Piwik::Goals::VisitsUntilConversion < ::Piwik::ApiResponse; end
class Piwik::ImageGraph < ::Piwik::ApiModule; end
class Piwik::ImageGraph::Get < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager < ::Piwik::ApiModule; end
class Piwik::LanguagesManager::AvailableLanguageNames < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager::AvailableLanguages < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager::AvailableLanguagesInfo < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager::IsLanguageAvailable < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager::LanguageForUser < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager::SetLanguageForUser < ::Piwik::ApiResponse; end
class Piwik::LanguagesManager::TranslationsForLanguage < ::Piwik::ApiResponse; end
class Piwik::Live < ::Piwik::ApiModule; end
class Piwik::Live::Counters < ::Piwik::ApiResponse; end
class Piwik::Live::LastVisitsDetails < ::Piwik::ApiResponse; end
class Piwik::MissingConfiguration < ::ArgumentError; end
class Piwik::MobileMessaging < ::Piwik::ApiModule; end
class Piwik::MobileMessaging::AreSMSAPICredentialProvided < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::CreditLeft < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::DelegatedManagement < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::PhoneNumber < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::RemovePhoneNumber < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::SMSAPICredential < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::SMSProvider < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::SetDelegatedManagement < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::SetSMSAPICredential < ::Piwik::ApiResponse; end
class Piwik::MobileMessaging::ValidatePhoneNumber < ::Piwik::ApiResponse; end
class Piwik::MultiSites < ::Piwik::ApiModule; end
class Piwik::MultiSites::All < ::Piwik::ApiResponse; end
class Piwik::MultiSites::One < ::Piwik::ApiResponse; end
class Piwik::PdfReports < ::Piwik::ApiModule; end
class Piwik::PdfReports::GenerateReport < ::Piwik::ApiResponse; end
class Piwik::PdfReports::Report < ::Piwik::ApiResponse; end
class Piwik::PdfReports::Reports < ::Piwik::ApiResponse; end
class Piwik::PdfReports::SendReport < ::Piwik::ApiResponse; end
class Piwik::PdfReports::UpdateReport < ::Piwik::ApiResponse; end
class Piwik::Provider < ::Piwik::ApiModule; end
class Piwik::Provider::Provider < ::Piwik::ApiResponse; end
Piwik::Referers = Piwik::Referrers
class Piwik::Referrers < ::Piwik::ApiModule; end
class Piwik::Referrers::Campaigns < ::Piwik::ApiResponse; end
class Piwik::Referrers::Keywords < ::Piwik::ApiResponse; end
class Piwik::Referrers::KeywordsForPageTitle < ::Piwik::ApiResponse; end
class Piwik::Referrers::KeywordsForPageUrl < ::Piwik::ApiResponse; end
class Piwik::Referrers::KeywordsFromCampaignId < ::Piwik::ApiResponse; end
class Piwik::Referrers::KeywordsFromSearchEngineId < ::Piwik::ApiResponse; end
class Piwik::Referrers::NumberOfDistinctCampaigns < ::Piwik::ApiResponse; end
class Piwik::Referrers::NumberOfDistinctKeywords < ::Piwik::ApiResponse; end
class Piwik::Referrers::NumberOfDistinctSearchEngines < ::Piwik::ApiResponse; end
class Piwik::Referrers::NumberOfDistinctWebsites < ::Piwik::ApiResponse; end
class Piwik::Referrers::NumberOfDistinctWebsitesUrls < ::Piwik::ApiResponse; end
class Piwik::Referrers::ReferrerType < ::Piwik::ApiResponse; end
class Piwik::Referrers::SearchEngines < ::Piwik::ApiResponse; end
class Piwik::Referrers::SearchEnginesFromKeywordId < ::Piwik::ApiResponse; end
class Piwik::Referrers::Socials < ::Piwik::ApiResponse; end
class Piwik::Referrers::UrlsForSocial < ::Piwik::ApiResponse; end
class Piwik::Referrers::UrlsFromWebsiteId < ::Piwik::ApiResponse; end
class Piwik::Referrers::Websites < ::Piwik::ApiResponse; end
class Piwik::SEO < ::Piwik::ApiModule; end
class Piwik::SEO::Rank < ::Piwik::ApiResponse; end
class Piwik::ScheduledReports < ::Piwik::ApiModule; end
class Piwik::ScheduledReports::GenerateReport < ::Piwik::ApiResponse; end
class Piwik::ScheduledReports::Report < ::Piwik::ApiResponse; end
class Piwik::ScheduledReports::Reports < ::Piwik::ApiResponse; end
class Piwik::ScheduledReports::SendReport < ::Piwik::ApiResponse; end
class Piwik::ScheduledReports::UpdateReport < ::Piwik::ApiResponse; end

class Piwik::Segment < ::Piwik::Base
  class << self
    def collection; end
    def id_attr; end
  end
end

class Piwik::SegmentEditor < ::Piwik::ApiModule
  class << self
    def add(params); end
    def delete(params); end
    def get(params); end
    def save(params); end
  end
end

class Piwik::SegmentEditor::Add < ::Piwik::ApiResponse; end
class Piwik::SegmentEditor::All < ::Piwik::ApiResponse; end
class Piwik::SegmentEditor::Delete < ::Piwik::ApiResponse; end
class Piwik::SegmentEditor::Get < ::Piwik::ApiResponse; end
class Piwik::SegmentEditor::IsUserCanAddNewSegment < ::Piwik::ApiResponse; end
class Piwik::SegmentEditor::Update < ::Piwik::ApiResponse; end

class Piwik::Site < ::Piwik::Base
  def actions; end
  def annotations; end
  def devices_detection; end
  def events; end
  def give_admin_access_to(login); end
  def give_no_access_to(login); end
  def give_view_access_to(login); end
  def goals; end
  def referrers; end
  def remove_access_for(login); end
  def scheduled_reports; end
  def seo_info; end
  def transitions; end
  def visits; end

  private

  def give_access_to(access, login); end

  class << self
    def collection; end
    def id_attr; end
  end
end

class Piwik::SitesManager < ::Piwik::ApiModule
  class << self
    def add(params); end
    def delete(params); end
    def get(params); end
    def save(params); end
  end
end

class Piwik::SitesManager::AllSites < ::Piwik::ApiResponse; end
class Piwik::SitesManager::AllSitesId < ::Piwik::ApiResponse; end
class Piwik::SitesManager::CurrencyList < ::Piwik::ApiResponse; end
class Piwik::SitesManager::CurrencySymbols < ::Piwik::ApiResponse; end
class Piwik::SitesManager::DefaultCurrency < ::Piwik::ApiResponse; end
class Piwik::SitesManager::DefaultTimezone < ::Piwik::ApiResponse; end
class Piwik::SitesManager::ExcludedIpsGlobal < ::Piwik::ApiResponse; end
class Piwik::SitesManager::ExcludedQueryParametersGlobal < ::Piwik::ApiResponse; end
class Piwik::SitesManager::ExcludedUserAgentsGlobal < ::Piwik::ApiResponse; end
class Piwik::SitesManager::IpsForRange < ::Piwik::ApiResponse; end
class Piwik::SitesManager::IsSiteSpecificUserAgentExcludeEnabled < ::Piwik::ApiResponse; end
class Piwik::SitesManager::JavascriptTag < ::Piwik::ApiResponse; end
class Piwik::SitesManager::PatternMatchSites < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SearchCategoryParametersGlobal < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SearchKeywordParametersGlobal < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetDefaultCurrency < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetDefaultTimezone < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetGlobalExcludedIps < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetGlobalExcludedQueryParameters < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetGlobalExcludedUserAgents < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetGlobalSearchParameters < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SetSiteSpecificUserAgentExcludeEnabled < ::Piwik::ApiResponse; end
class Piwik::SitesManager::Site < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SiteAliasUrls < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SiteFromId < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SiteUrlsFromId < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesFromGroup < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesGroups < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesIdFromSiteUrl < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesIdWithAdminAccess < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesIdWithAtLeastViewAccess < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesIdWithViewAccess < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesIdWithVisits < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesWithAdminAccess < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesWithAtLeastViewAccess < ::Piwik::ApiResponse; end
class Piwik::SitesManager::SitesWithViewAccess < ::Piwik::ApiResponse; end
class Piwik::SitesManager::TimezonesList < ::Piwik::ApiResponse; end
class Piwik::SitesManager::UniqueSiteTimezones < ::Piwik::ApiResponse; end
class Piwik::SitesManager::UpdateSite < ::Piwik::ApiResponse; end
class Piwik::Transitions < ::Piwik::ApiModule; end
class Piwik::Transitions::TransitionsForAction < ::Piwik::ApiResponse; end
class Piwik::Transitions::TransitionsForPageTitle < ::Piwik::ApiResponse; end
class Piwik::Transitions::TransitionsForPageUrl < ::Piwik::ApiResponse; end
class Piwik::Transitions::Translations < ::Piwik::ApiResponse; end

module Piwik::Typecast
  include ::Piwik::Typecast::InstanceMethods

  class << self
    def included(base); end
  end
end

module Piwik::Typecast::InstanceMethods
  private

  def typecast(thing); end
end

class Piwik::UnknownGoal < ::ArgumentError; end
class Piwik::UnknownSite < ::ArgumentError; end
class Piwik::UnknownUser < ::ArgumentError; end

class Piwik::User < ::Piwik::Base
  class << self
    def collection; end
    def id_attr; end
  end
end

class Piwik::UserCountry < ::Piwik::ApiModule; end
class Piwik::UserCountry::City < ::Piwik::ApiResponse; end
class Piwik::UserCountry::Continent < ::Piwik::ApiResponse; end
class Piwik::UserCountry::Country < ::Piwik::ApiResponse; end
class Piwik::UserCountry::LocationFromIP < ::Piwik::ApiResponse; end
class Piwik::UserCountry::NumberOfDistinctCountries < ::Piwik::ApiResponse; end
class Piwik::UserCountry::Region < ::Piwik::ApiResponse; end
class Piwik::UserSettings < ::Piwik::ApiModule; end
class Piwik::UserSettings::Browser < ::Piwik::ApiResponse; end
class Piwik::UserSettings::BrowserType < ::Piwik::ApiResponse; end
class Piwik::UserSettings::BrowserVersion < ::Piwik::ApiResponse; end
class Piwik::UserSettings::Configuration < ::Piwik::ApiResponse; end
class Piwik::UserSettings::MobileVsDesktop < ::Piwik::ApiResponse; end
class Piwik::UserSettings::OS < ::Piwik::ApiResponse; end
class Piwik::UserSettings::OSFamily < ::Piwik::ApiResponse; end
class Piwik::UserSettings::Plugin < ::Piwik::ApiResponse; end
class Piwik::UserSettings::Resolution < ::Piwik::ApiResponse; end
class Piwik::UserSettings::WideScreen < ::Piwik::ApiResponse; end

class Piwik::UsersManager < ::Piwik::ApiModule
  class << self
    def add(params); end
    def delete(params); end
    def get(params); end
    def save(params); end
    def user_exists(params); end
  end
end

class Piwik::UsersManager::SetUserAccess < ::Piwik::ApiResponse; end
class Piwik::UsersManager::SetUserPreference < ::Piwik::ApiResponse; end
class Piwik::UsersManager::SitesAccessFromUser < ::Piwik::ApiResponse; end
class Piwik::UsersManager::TokenAuth < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UpdateUser < ::Piwik::ApiResponse; end
class Piwik::UsersManager::User < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UserByEmail < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UserEmailExists < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UserExists < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UserPreference < ::Piwik::ApiResponse; end
class Piwik::UsersManager::Users < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UsersAccessFromSite < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UsersLogin < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UsersSitesFromAccess < ::Piwik::ApiResponse; end
class Piwik::UsersManager::UsersWithSiteAccess < ::Piwik::ApiResponse; end
Piwik::VERSION = T.let(T.unsafe(nil), String)
class Piwik::VisitFrequency < ::Piwik::ApiModule; end
class Piwik::VisitFrequency::Get < ::Piwik::ApiResponse; end
class Piwik::VisitTime < ::Piwik::ApiModule; end
class Piwik::VisitTime::ByDayOfWeek < ::Piwik::ApiResponse; end
class Piwik::VisitTime::VisitInformationPerLocalTime < ::Piwik::ApiResponse; end
class Piwik::VisitTime::VisitInformationPerServerTime < ::Piwik::ApiResponse; end
class Piwik::VisitorInterest < ::Piwik::ApiModule; end
class Piwik::VisitorInterest::NumberOfVisitsByDaysSinceLast < ::Piwik::ApiResponse; end
class Piwik::VisitorInterest::NumberOfVisitsByVisitCount < ::Piwik::ApiResponse; end
class Piwik::VisitorInterest::NumberOfVisitsPerPage < ::Piwik::ApiResponse; end
class Piwik::VisitorInterest::NumberOfVisitsPerVisitDuration < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary < ::Piwik::ApiModule; end
class Piwik::VisitsSummary::Actions < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::BounceCount < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::Get < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::MaxActions < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::SumVisitsLength < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::SumVisitsLengthPretty < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::UniqueVisitors < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::Visits < ::Piwik::ApiResponse; end
class Piwik::VisitsSummary::VisitsConverted < ::Piwik::ApiResponse; end

class String
  include ::Comparable
  include ::JSON::Ext::Generator::GeneratorMethods::String
  extend ::JSON::Ext::Generator::GeneratorMethods::String::Extend

  def is_binary_data?; end
end

String::BLANK_RE = T.let(T.unsafe(nil), Regexp)
String::ENCODED_BLANKS = T.let(T.unsafe(nil), Concurrent::Map)
