# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bootstrap` gem.
# Please instead update this file by running `bin/tapioca gem bootstrap`.

module Bootstrap
  class << self
    def assets_path; end
    def gem_path; end
    def hanami?; end
    def javascripts_path; end
    def load!; end
    def rails?; end
    def sprockets?; end
    def stylesheets_path; end

    private

    def register_hanami; end
    def register_rails_engine; end
    def register_sprockets; end
  end
end

Bootstrap::BOOTSTRAP_SHA = T.let(T.unsafe(nil), String)
module Bootstrap::Rails; end
class Bootstrap::Rails::Engine < ::Rails::Engine; end
Bootstrap::VERSION = T.let(T.unsafe(nil), String)
