# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `chromedriver-helper` gem.
# Please instead update this file by running `bin/tapioca gem chromedriver-helper`.

module Chromedriver
  class << self
    def set_version(version); end
  end
end

class Chromedriver::Helper
  def base_install_dir; end
  def binary_path; end
  def current_version; end
  def download(hit_network = T.unsafe(nil)); end
  def download_url; end
  def download_version; end
  def google_code_parser; end
  def platform; end
  def platform_install_dir; end
  def run(*args); end
  def update(version = T.unsafe(nil)); end
  def version_install_dir; end
  def version_path; end
end

class Chromedriver::Helper::GoogleCodeParser
  def initialize(platform, open_uri_provider = T.unsafe(nil)); end

  def downloads; end
  def newest_download_version; end
  def platform; end
  def source; end
  def version_download_url(version); end

  private

  def grab_version_string_from(url); end
  def version_of(url); end
end

Chromedriver::Helper::GoogleCodeParser::BUCKET_URL = T.let(T.unsafe(nil), String)
Chromedriver::Helper::VERSION = T.let(T.unsafe(nil), String)
