# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-reddit` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-reddit`.

module OmniAuth
  class << self
    def config; end
    def configure; end
    def logger; end
    def mock_auth_for(provider); end
    def strategies; end
  end
end

module OmniAuth::Reddit; end
OmniAuth::Reddit::VERSION = T.let(T.unsafe(nil), String)
module OmniAuth::Strategies; end

class OmniAuth::Strategies::Reddit < ::OmniAuth::Strategies::OAuth2
  def basic_auth_header; end
  def build_access_token; end
  def callback_url; end
  def mobile_request?; end
  def raw_info; end
  def request_phase; end
end

OmniAuth::Strategies::Reddit::MOBILE_USER_AGENTS = T.let(T.unsafe(nil), String)
OmniAuth::VERSION = T.let(T.unsafe(nil), String)
