inherit_from:
  - .rubocop_airbnb.yml

Layout/AlignParameters:
  Enabled: false
Style/Documentation:
  Enabled: false
AllCops:
  Include:
    - config.ru
    - Gemfile
    - Rakefile
    - app/models/**/*
    - app/controllers/publishers_controller.rb
    - app/controllers/publishers/paypal_accounts_controller.rb
    - app/controllers/publishers/registrations_controller.rb
    - app/controllers/admin/publisher_notes_controller.rb
    - app/controllers/admin/publishers_controller.rb
    - app/controllers/admin/publishers/publisher_status_updates_controller.rb
    - app/controllers/admin/unattached_promo_registrations_controller.rb
    - app/controllers/publishers/cases_controller.rb
    - app/controllers/publishers/**
    - app/controllers/payment/**
    - app/helpers/publishers_helper.rb
    - app/services/uphold/**/*
    - app/services/paypal/**
    - app/services/gemini/**
    - app/jobs/connections/**/*
    - app/jobs/channels/**/*
    - app/jobs/create_uphold_cards_job.rb
    - app/jobs/create_uphold_channel_card_job.rb
    - app/jobs/exchange_uphold_code_for_access_token_job.rb
    - app/jobs/clean_stale_uphold_data_job.rb
    - app/jobs/payout/**/*
    - app/jobs/include_publisher_in_payout_report_job.rb
    - app/services/payout_report_publisher_includer.rb
    - app/services/promo/unattached_registrar.rb
    - app/services/promo/registrations_geo_stats_fetcher.rb
    - test/services/**/*
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
Metrics/LineLength:
  Max: 400
Airbnb/DefaultScope:
  Enabled: false
Airbnb/SimpleModifierConditional:
  Enabled: false
Airbnb/SimpleUnless:
  Enabled: false
Airbnb/UnsafeYamlMarshal:
  Enabled: false
Style/AndOr:
  Enabled: false
