inherit_from:
  - .rubocop_airbnb.yml

AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  Include:
    - config.ru
    - Gemfile
    - Rakefile
    - app/models/**/*
  Exclude:
    - bin/**/*
    - db/**/*
LineLength:
  Max: 225
