inherit_from:
  - .rubocop_airbnb.yml

AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  Include:
    - config.ru
    - Gemfile
    - Rakefile
    - app/models/**/*
    - app/controllers/publishers_controller.rb
    - app/controllers/publishers/registrations_controller.rb
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
LineLength:
  Max: 400
Airbnb/SimpleModifierConditional:
  Enabled: false
Airbnb/DefaultScope:
  Enabled: false
Airbnb/SimpleUnless:
  Enabled: false
Style/AndOr:
  Enabled: false
