inherit_from:
  - .rubocop_airbnb.yml

AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  Include:
    - config.ru
    - Gemfile
    - Rakefile
    - app/models/**/*
    - app/controllers/publishers_controller.rb
    - app/controllers/publishers/registrations_controller.rb
    - app/controllers/admin/publisher_notes_controller.rb
    - app/controllers/admin/publishers_controller.rb
    - app/controllers/admin/publishers/publisher_status_updates_controller.rb
    - app/controllers/publishers/cases_controller.rb
    - app/controllers/publishers/uphold_controller.rb
    - app/services/uphold/**/*
    - app/jobs/create_uphold_cards_job.rb
    - app/jobs/exchange_uphold_code_for_access_token_job.rb
    - app/jobs/clean_stale_uphold_data_job.rb
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
LineLength:
  Max: 400
Airbnb/SimpleModifierConditional:
  Enabled: false
Airbnb/DefaultScope:
  Enabled: false
Airbnb/SimpleUnless:
  Enabled: false
Style/AndOr:
  Enabled: false
