# fix: true               # default: false
parallel: true          # default: false
# format: progress        # default: Standard::Formatter
# ruby_version: 2.3.3     # default: RUBY_VERSION
default_ignores: true   # default: true

ignore:                 # default: []
  - Lint/ConstantDefinitionInBlock
  - 'db/**/*'
  - 'vendor/**/*'
  - 'bin/**/*'
  - 'protos/**/*'
  - 'config/puma.rb'
  - 'config/environments/**'
  