local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_internal_bucket:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_public_bucket:
  service: Disk
  root: <%= Rails.root.join("storage") %>
