test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon_case_notes:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon_banner_images:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
