name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 🎨 Stylelint, and 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: ⎔ Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: u0reo/npm-install@fix/restore-failure
        with:
          useRollingCache: true

      - name: 🔬 Lint
        run: npm run lint:strict

      - name: 🎨 Stylelint
        run: npm run stylelint

      - name: 🔎 Type check
        run: npm run typecheck

      - name: 🃏 Run jest
        run: npm run test

      - name: 🦁 Brave Leo audit
        run: npm exec leo-check
