name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 🎨 Stylelint, and 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ⎔ Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: u0reo/npm-install@fix/restore-failure
        with:
          useRollingCache: true

      - name: 🔬 Lint
        run: npm run lint:strict

      - name: 🎨 Stylelint
        run: npm run stylelint

      - name: 🔎 Type check
        run: npm run typecheck

      - name: 🃏 Run jest
        run: npm run test

      - name: 🦁 Brave Leo audit
        run: npm exec leo-check
