name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, 🎨 Stylelint, and 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: ⎔ Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 22

      - name: 📥 Download deps
        uses: u0reo/npm-install@fix/restore-failure
        with:
          useRollingCache: true

      - name: 🔬 Lint
        run: npm run lint:strict

      - name: 🎨 Stylelint
        run: npm run stylelint

      - name: 🔎 Type check
        run: npm run typecheck

      - name: 🃏 Run jest
        run: npm run test

      - name: 🦁 Brave Leo audit
        run: npm exec leo-check
