default: &default
  cloudfront: <%= ENV["CLOUDFRONT_API"] || "https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips" %>

test:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
