default: &default
  cloudfront: <%= ENV["CLOUDFRONT_API"] || "https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips" %>
  gemini:
    api_uri: <%= ENV["GEMINI_API"] || "https://api.sandbox.gemini.com" %>
    oauth_uri: <%= ENV["GEMINI_OAUTH_API"] || "https://exchange.sandbox.gemini.com" %>
    client_id: <%= ENV["GEMINI_CLIENT_ID"] || 'fake-client-id' %> 
    client_secret: <%= ENV["GEMINI_CLIENT_SECRET"] || 'fake-client-secret' %> 
  stripe:
    publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
    client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
    client_secret: <%= ENV["STRIPE_SECRET_KEY"] %>

test:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
