default: &default
  fastly: <%= ENV["FASTLY_API"] || "https://api.fastly.com/public-ip-list" %>
  gemini:
    api_uri: <%= ENV["GEMINI_API"] || "https://api.sandbox.gemini.com" %>
    oauth_uri: <%= ENV["GEMINI_OAUTH_API"] || "https://exchange.sandbox.gemini.com" %>
    client_id: <%= ENV["GEMINI_CLIENT_ID"] %>
    client_secret: <%= ENV["GEMINI_CLIENT_SECRET"] %>
  stripe:
    publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
    client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
    client_secret: <%= ENV["STRIPE_SECRET_KEY"] %>

test:
  <<: *default
  # In our test files we should ensure we're mocking all these requests.
  # So we're going to be passing invalid URLs so if any of our tests aren't mocked then Faraday will raise an exception.
  gemini:
    api_uri: https://api.gemini.fake
    oauth_uri: https://exchange.gemini.fake

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
