# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

module ::Partner; end
module ::Publisher; end
module ::Publisher::ActiveRecord_Associations_CollectionProxy; end
module Devise::RouteSet; end
module Rake::TaskLib; end
module T::Private::Methods::Signature; end
