
name: Generalized Deployments
on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  push:
    name: Invoke General Docker Build Pipeline
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
      with:
        role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
        aws-region: us-west-2
    - name: Generalized Deployments
      uses: brave-intl/general-docker-build-pipeline-action@50a99c1f051b1d8e20ed79ded2e69ab3153b66e4 # v1.0.25
