
name: Generalized Deployments
on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  push:
    name: Invoke General Docker Build Pipeline
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
        aws-region: us-west-2
    - name: Generalized Deployments
      uses: brave-intl/general-docker-build-pipeline-action@50a99c1f051b1d8e20ed79ded2e69ab3153b66e4 # v1.0.25
