# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
     
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install dependencies
        run: bundle install
      - name: Prepare database
        run: bundle exec rake db:prepare
        env: 
          DATABASE_URL_TEST: postgres://postgres@postgres:5432/brave_publishers_test
      - name: Run tests
        run: bundle exec rails test
        env: 
          DATABASE_URL_TEST: postgres://postgres@postgres:5432/brave_publishers_test
      - name: Brakeman
        run: bundle exec brakeman
      - name: Rubocop
        run: bundle exec rubocop
