name: "Semgrep App"

on:
  pull_request:
  push:
    branches:
      - master
      - staging
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '0 0 1 * *'

jobs:
  analyze:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
